---
# Firewalld enablement

- name: Enable firewalld
  become: true
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Enable Firewall port 4730
  become: true
  firewalld:
    port: 4730/tcp
    state: enabled
    permanent: true
    immediate: true

