---
# tasks file for infra_xxx

- when: grafana_host_state != 'absent'
  block:

    - name: Create server {{ grafana_host_server_name }}
      os_server:
        state: "{{ grafana_host_state }}"
        name: "{{ grafana_host_server_name }}"
        image: "{{ grafana_host_image }}"
        flavor: "{{ grafana_host_flavor }}"
        key_name: "{{ grafana_host_key_name }}"
        boot_from_volume: true
        auto_ip: "{{ grafana_host_auto_ip }}"
        meta: "{{ grafana_host_metadata }}"
        availability_zone: "{{ grafana_host_availability_zone }}"
        security_groups: "{{ grafana_host_security_groups }}"
        nics: "{{ grafana_host_network }}"
        volume_size: "{{ grafana_host_root_volume_size }}"
        userdata: |
          #cloud-config
          fqdn: {{ grafana_host_server_fqdn }}
          packages:
          growpart:
          mode: auto
          devices: ['/']
          ignore_growroot_disabled: false
      register: server

    - name: Create Data Volume {{ grafana_host_data_volume_name }}
      os_volume:
        state: "{{ grafana_host_state }}"
        name: "{{ grafana_host_data_volume_name }}"
        size: "{{ grafana_host_data_volume_size }}"
        volume_type: "{{ grafana_host_data_volume_type }}"
        availability_zone: "{{ grafana_host_availability_zone }}"
        metadata: "{{ grafana_host_data_volume_metadata }}"
      when: grafana_host_data_volume_size is defined
      register: data_volume

    - name: Attach Data Volume {{ grafana_host_data_volume_name }}
      os_server_volume:
        state: present
        server: "{{ server.id }}"
        volume: "{{ data_volume.id }}"
      when: data_volume.id is defined

- when: grafana_host_state == 'absent'
  block:

    - name: Delete host
      os_server:
        state: absent
        name: "{{ grafana_host_server_name }}"

    - name: Delete volume
      os_volume:
        state: absent
        name: "{{ grafana_host_data_volume_name }}"
