---
# defaults file for roles/grafana
grafana_systemd_service_name: "grafana.service"
grafana_systemd_unit_path: "{{ '/etc/systemd/system/' + grafana_systemd_service_name }}"
grafana_security_admin_password: "foobar"
grafana_image_tag: "6.5.0"
grafana_users_allow_sign_up: false

grafana_enable_renderer: false
grafana_renderer_systemd_service_name: "grafana-renderer.service"
grafana_renderer_systemd_unit_path: "{{ '/etc/systemd/system/' + grafana_renderer_systemd_service_name }}"
grafana_renderer_hosts_entries: []
grafana_renderer_image_tag: "2.0.0"
grafana_renderer_host: renderer
grafana_grafana_host: grafana

grafana_users_login_hint: username
grafana_users_password_hint: password

grafana_os_user: grafana
grafana_os_group: grafana

grafana_enable_ssl: true
grafana_ssl_cert_name: grafana.cert
grafana_ssl_cert_location: "/etc/ssl/certs/{{ grafana_ssl_cert_name }}"
grafana_ssl_cert_content:
grafana_ssl_key_name: grafana.key
grafana_ssl_key_location: "/etc/ssl/certs/{{ grafana_ssl_key_name }}"
grafana_ssl_key_content:

grafana_auth_github_enable: false

grafana_plugins: []

packages: []

# Infra defaults
grafana_host_state: "present"
grafana_host_image: "Standard_Fedora_30_latest"
grafana_host_flavor: "s2.xlarge.2"
grafana_host_server_name: "{{ ('grafana.' + domain_name) | default('grafana') }}"
grafana_host_availability_zone: "eu-de-03"
grafana_host_root_volume_size: 12
grafana_host_data_volume_name: "grafana_data"
grafana_host_data_volume_size: 20
grafana_host_data_volume_type: "SSD"
# Auto attach FIP
grafana_host_auto_ip: false

grafana_host_metadata:
  host-type: grafana
grafana_host_data_volume_metadata:
  host-type: grafana


grafana_auth_ldap_enable: false 
grafana_auth_ldap_certificate: |
  dummy-ca-cert
grafana_auth_ldap_host: '"ldap.example.com"'
grafana_auth_ldap_hosts_entries: ["ldap.example.com:1.2.3.4"]
grafana_auth_ldap_bind_dn:  '"cn=proxy,ou=profile,dc=example,dc=com"'
grafana_auth_ldap_bind_password: 'foobar'
grafana_auth_ldap_search_filter:  '"(uid=%s)"'
grafana_auth_ldap_search_base_dns:  '["ou=people,dc=example,dc=com"]'
grafana_auth_ldap_group_search_filter:  '"(&(objectClass=posixGroup)(memberUid=%s))"'
grafana_auth_ldap_group_search_filter_user_attribute:  '"uid"'
grafana_auth_ldap_group_dn_super_admin:  "cn=grafana-super-admins,ou=group,dc=example,dc=com"
grafana_auth_ldap_group_dn_admin:  "cn=grafana-admins,ou=group,dc=example,dc=com"
grafana_auth_ldap_group_dn_editor: "cn=grafana-editors,ou=group,dc=example,dc=com"
grafana_auth_ldap_group_search_base_dns: [ " {{ grafana_auth_ldap_group_dn_super_admin }} ", " {{ grafana_auth_ldap_group_dn_admin }} ", " {{ grafana_auth_ldap_group_dn_editor }} " ]
