---
# handlers file for roles/grafana

- name: restart grafana
  become: true
  systemd:
    name: "{{ grafana_systemd_service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart grafana-renderer
  become: true
  systemd:
    name: "{{ grafana_renderer_systemd_service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
